version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: db
      DB_USER: user
      DB_PASSWORD: password
      JWT_SECRET: dev-secret
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db_data: {}
